# Generated by Django 5.2.6 on 2025-09-30 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactmessage",
            name="phone",
            field=models.CharField(default=1, max_length=15, verbose_name="شماره تلفن"),
            preserve_default=False,
        ),
    ]
